import type { AuthCopy, Locale } from './authTypes'

export const authCopy: Record<Locale, AuthCopy> = {
  ru: {
    title: 'Войти',
    registerTitle: 'Регистрация',
    forgotPasswordTitle: 'Забыли пароль?',
    emailLabel: 'Email',
    emailPlaceholder: 'Введите Email',
    passwordLabel: 'Пароль',
    confirmPasswordLabel: 'Подтвердите пароль',
    passwordPlaceholder: 'Введите пароль',
    passwordMismatch: 'Пароли не совпадают',
    passwordMinLength: 'Минимум 8 символов',
    invalidCredentialsTitle: 'Неправильный Email или пароль',
    invalidCredentialsText: 'Введите данные повторно',
    duplicateAccountTitle: 'Аккаунт уже существует',
    duplicateAccountText:
      'Пользователь с таким Email уже зарегистрирован. Попробуйте войти.',
    profileUnavailableTitle: 'Профиль еще не готов',
    profileUnavailableText:
      'Аккаунт создан, но профиль не удалось получить из базы. Попробуйте войти через несколько секунд.',
    rateLimitTitle: 'Слишком много попыток',
    rateLimitText: 'Подождите немного и попробуйте снова.',
    samePasswordTitle: 'Пароль не изменился',
    samePasswordText: 'Новый пароль должен отличаться от текущего.',
    sessionExpiredTitle: 'Ссылка устарела',
    sessionExpiredText:
      'Запросите новое письмо для восстановления пароля и перейдите по свежей ссылке.',
    retryInputText: 'Введите данные повторно',
    unknownErrorTitle: 'Неизвестная ошибка',
    unknownErrorText:
      'Что-то пошло не так. Возможно, сбой в сети или на сервере. Попробуйте чуть позже.',
    forgotPassword: 'Забыли пароль?',
    forgotPasswordHint:
      'Укажите свой email, и мы отправим ссылку для восстановления пароля',
    passwordSentTitle: 'Письмо отправлено',
    passwordSentText:
      'Проверьте свою почту - мы отправили ссылку для восстановления пароля. Если письма нет, загляните в папку "Спам". Все равно не пришло? Запросите повторную отправку.',
    confirmationSentTitle: 'Письмо отправлено',
    confirmationSentText:
      'Проверьте свою почту - мы отправили ссылку для подтверждения аккаунта. После подтверждения вернитесь и войдите в аккаунт.',
    confirmationSentAction: 'Перейти ко входу',
    newPasswordTitle: 'Новый пароль',
    newPasswordLabel: 'Новый пароль',
    passwordUpdatedTitle: 'Пароль обновлен',
    passwordUpdatedText: 'Теперь можно войти с новым паролем.',
    savePassword: 'Сохранить пароль',
    backToLogin: 'Вернуться ко входу в аккаунт',
    resend: 'Отправить повторно',
    send: 'Отправить',
    sending: 'Отправляем...',
    submit: 'Войти',
    noAccount: 'Нет аккаунта?',
    createAccount: 'Создать аккаунт',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    next: 'Далее',
    agreementPrefix: 'Продолжая, вы соглашаетесь с',
    terms: 'Условиями использования',
    agreementMiddle: 'и',
    privacy: 'Политикой конфиденциальности',
    mapFallbackTitle: 'Карта недоступна',
    mapFallbackText: 'Проверьте ключ Google Maps в .env.',
    showPassword: 'Показать пароль',
    hidePassword: 'Скрыть пароль',
  },
  en: {
    title: 'Sign in',
    registerTitle: 'Registration',
    forgotPasswordTitle: 'Forgot password?',
    emailLabel: 'Email',
    emailPlaceholder: 'Enter email',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm password',
    passwordPlaceholder: 'Enter password',
    passwordMismatch: 'Passwords do not match',
    passwordMinLength: 'Minimum 8 characters',
    invalidCredentialsTitle: 'Incorrect email or password',
    invalidCredentialsText: 'Please enter your details again',
    duplicateAccountTitle: 'Account already exists',
    duplicateAccountText:
      'A user with this email is already registered. Try signing in.',
    profileUnavailableTitle: 'Profile is not ready yet',
    profileUnavailableText:
      'The account was created, but the profile could not be loaded from the database. Try signing in again in a few seconds.',
    rateLimitTitle: 'Too many attempts',
    rateLimitText: 'Please wait a moment and try again.',
    samePasswordTitle: 'Password was not changed',
    samePasswordText: 'Your new password must be different from the current one.',
    sessionExpiredTitle: 'Link expired',
    sessionExpiredText:
      'Request a new password recovery email and open the fresh link.',
    retryInputText: 'Please enter your details again',
    unknownErrorTitle: 'Unknown error',
    unknownErrorText:
      'Something went wrong. It may be a network or server issue. Please try again later.',
    forgotPassword: 'Forgot password?',
    forgotPasswordHint:
      'Enter your email and we will send you a password recovery link',
    passwordSentTitle: 'Email sent',
    passwordSentText:
      'Check your inbox - we sent you a password recovery link. If there is no email, check your Spam folder. Still nothing? Request another email.',
    confirmationSentTitle: 'Email sent',
    confirmationSentText:
      'Check your inbox - we sent you an account confirmation link. After confirming, return and sign in.',
    confirmationSentAction: 'Go to sign in',
    newPasswordTitle: 'New password',
    newPasswordLabel: 'New password',
    passwordUpdatedTitle: 'Password updated',
    passwordUpdatedText: 'You can now sign in with your new password.',
    savePassword: 'Save password',
    backToLogin: 'Return to sign in',
    resend: 'Send again',
    send: 'Send',
    sending: 'Sending...',
    submit: 'Sign in',
    noAccount: 'No account?',
    createAccount: 'Create account',
    alreadyHaveAccount: 'Already have an account?',
    next: 'Next',
    agreementPrefix: 'By continuing, you agree to the',
    terms: 'Terms of Use',
    agreementMiddle: 'and',
    privacy: 'Privacy Policy',
    mapFallbackTitle: 'Map is unavailable',
    mapFallbackText: 'Check the Google Maps key in .env.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
  },
}
